#!/bin/zsh
set -euo pipefail

CLI=/Users/x32db/PROJECTS/claude-code/dist/claude-darwin-x64

export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-${VEXZY_API_KEY:-}}"
: "${ANTHROPIC_API_KEY:?Set VEXZY_API_KEY or ANTHROPIC_API_KEY before launching claude}"
export ANTHROPIC_BASE_URL="${ANTHROPIC_BASE_URL:-https://api.echogate.one}"
export ANTHROPIC_MODEL="${ANTHROPIC_MODEL:-gpt-5.6-luna}"
export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS="1"
export CLAUDE_CODE_SUBAGENT_MODEL="gpt-5.6-luna"
export CLAUDE_CODE_COMPACT_MODEL="gpt-5.6-luna"
export CLAUDE_CODE_MAX_WORKERS="${CLAUDE_CODE_MAX_WORKERS:-20}"
export CLAUDE_CODE_DELEGATION_FIRST="1"
export CLAUDE_AUTOCOMPACT_PCT_OVERRIDE="${CLAUDE_AUTOCOMPACT_PCT_OVERRIDE:-85}"
export CLAUDE_CODE_DISABLE_COMPACT_CACHE_SHARING="1"
unset CLAUDE_CODE_SIMPLE DISABLE_COMPACT DISABLE_AUTO_COMPACT

exec "$CLI" "$@"
